### ISSUE TITLE
Django 1.8 tests fail

### ISSUE THREAD

**Issue by brianmay** [Atomidata/django-audit-log#29]
Example error:

```
======================================================================
ERROR: test_fields (audit_log.tests.audit_log_tests.test_logging.TestOneToOne)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/audit_log/tests/audit_log_tests/test_logging.py", line 213, in test_fields
    self.run_client(c)
  File "/<<PKGBUILDDIR>>/audit_log/tests/audit_log_tests/test_logging.py", line 206, in run_client
    client.post('/propertyowner/create/', {'name': 'John Dory'})
  File "/usr/lib/python2.7/dist-packages/django/test/client.py", line 512, in post
    secure=secure, **extra)
  File "/usr/lib/python2.7/dist-packages/django/test/client.py", line 313, in post
    secure=secure, **extra)
  File "/usr/lib/python2.7/dist-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/lib/python2.7/dist-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py", line 249, in post
    return super(BaseCreateView, self).post(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py", line 213, in post
    form = self.get_form()
  File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py", line 73, in get_form
    form_class = self.get_form_class()
  File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py", line 150, in get_form_class
    "the 'fields' attribute is prohibited." % self.__class__.__name__
ImproperlyConfigured: Using ModelFormMixin (base class of PropertyOwnerCreateView) without the 'fields' attribute is prohibited.
```

**Comment by brianmay** [comment]
Looks like this may have been fixed in b633b5e766a8905a936175c62ec0412264782e56
