### ISSUE TITLE
auditlog error in django 1.11

### ISSUE THREAD

**Issue by DonOzone** [Atomidata/django-audit-log#45]
Hi,

I installed django 1.11 and followed the doc to add 'audit-log' MIDDLEWARE, the migrate was doing success, however, when I start run_server, the below error shows:
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9567d38510>
Traceback (most recent call last):
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 147, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 68, in get_handler
    return get_internal_wsgi_application()
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/oscar/venvs/acnts_env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/srv/apps/oo/accounts/accounts/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/oscar/venvs/acnts_env/lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object() takes no parameters

Though when I comment out the line:
#'audit_log.middleware.UserLoggingMiddleware',

The app would run without errors

**Comment by jeacaveo** [comment]
Found the same problem.

In Django 1.10 the load_middleware method doesn't use a parameter to create an instance of the middlewarer: 

https://github.com/django/django/blob/stable/1.10.x/django/core/handlers/base.py#L58

In Django 1.11 this has changed to use a `handler` parameter:

https://github.com/django/django/blob/master/django/core/handlers/base.py#L41

**Comment by jeacaveo** [comment]
Found the problem, created PR #47 with fix. cc @DonOzone

**Comment by falava-carsegsa** [comment]
Any solution for this problem? When the PR #47 will be approved?

**Comment by iwalucas** [comment]
Same issue here, any deadline for the fix?

**Comment by artemijan** [comment]
any updates?

**Comment by kpy21ui** [comment]
Any solution for this problem? When the PR #47 will be approved?
