### ISSUE TITLE
Makemigrations error

### ISSUE THREAD

**Issue by AliYmn** [Atomidata/django-audit-log#66]
(env) ali@aliymn:~/portal-2.0$ python3 manage.py makemigrations
    /home/ali/env/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
    """)
    Traceback (most recent call last):
    File "manage.py", line 12, in <module>
        execute_from_command_line(sys.argv)
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
        utility.execute()
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
        self.execute(*args, **cmd_options)
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
        self.check()
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
        include_deployment_checks=include_deployment_checks,
    File "/home/ali/env/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
        return checks.run_checks(**kwargs)
    File "/home/ali/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
        new_errors = check(app_configs=app_configs)
    File "/home/ali/env/lib/python3.6/site-packages/debug_toolbar/apps.py", line 34, in check_middleware
        if is_middleware_class(GZipMiddleware, middleware):
    File "/home/ali/env/lib/python3.6/site-packages/debug_toolbar/apps.py", line 78, in is_middleware_class
        middleware_cls = import_string(middleware_path)
    File "/home/ali/env/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
        module = import_module(module_path)
    File "/home/ali/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 994, in _gcd_import
    File "<frozen importlib._bootstrap>", line 971, in _find_and_load
    File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 678, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/ali/env/lib/python3.6/site-packages/audit_log/middleware.py", line 5, in <module>
        from audit_log.models import fields
    File "/home/ali/env/lib/python3.6/site-packages/audit_log/models/__init__.py", line 5, in <module>
        class AuthStampedModel(Model):
    File "/home/ali/env/lib/python3.6/site-packages/audit_log/models/__init__.py", line 10, in AuthStampedModel
        created_by = CreatingUserField(verbose_name = _("created by"), related_name = "created_%(app_label)s_%(class)s_set")
    File "/home/ali/env/lib/python3.6/site-packages/audit_log/models/fields.py", line 14, in __init__
        super(LastUserField, self).__init__(to = to, null = null, editable = editable, **kwargs)
    TypeError: __init__() missing 1 required positional argument: 'on_delete

**Comment by AliYmn** [comment]
i am sorry, it was based on my project.
